baseurl = "https://jeffquast.com/"
languageCode = "en-us"
title = "Articles"
theme = "hugo-hikari-theme"
canonifyurls = true

[params]
        markup = "rst"
	name = "Jeff Quast"
	description = "Software Engineer"
	copyright = "have a day."
	newer = "Newer"
	older = "Older"
	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Jeff Quast"
	bio = "Software Engineer"
	subscribe = "Subscribe"
	followme = "contact@jeffquast.com"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/jquast"

	[[params.offcanvas.socialnetworks]]
		name = "Linkedin"
		url = "//linkedin.com/jeffreyquast"

	[[params.offcanvas.socialnetworks]]
		name = "PDF Resume"
		url = "/resume-jquast.pdf"
