[tox]
skipsdist=True

[testenv:minify]
skip_install = True
allowlist_externals = npx
commands = npx --yes esbuild src/simcity-embed.js --minify --target=es2022 \
               --outfile=content/post/a-perfect-simcity/simcity-embed.js

[testenv:build]
deps = docutils
       pygments
allowlist_externals = hugo, rst2html, pygments, pygmentize, npx, python3
commands = npx --yes esbuild src/simcity-embed.js --minify --target=es2022 \
               --outfile=content/post/a-perfect-simcity/simcity-embed.js
           python3 src/slim-engine-data.py
           hugo --theme=hugo-hikari-theme -d upload -F

[testenv:develop]
deps = docutils
       pygments
allowlist_externals = hugo, pygments, npx, python3
commands = npx --yes esbuild src/simcity-embed.js --minify --target=es2022 \
               --outfile=content/post/a-perfect-simcity/simcity-embed.js
           python3 src/slim-engine-data.py
           hugo --disableFastRender --theme=hugo-hikari-theme -w server -d /tmp/hugo-develop

[testenv:publish]
allowlist_externals = timeout
deps = awscli
commands = aws s3 sync --exclude '*.DS_Store*' --acl=public-read upload/ s3://jeff-quast/
           aws cloudfront create-invalidation --distribution-id E2IBSNWZPWFZZZ --paths "/*"
           timeout 300 bash -c 'echo -n waiting for invalidation ; sleep 10; while aws cloudfront list-invalidations --distribution-id E2KWZWQNFG8Q7F | grep -q InProgress; do sleep 5; echo -n '.'; done; echo'
